OpenDataPolicingNC/Traffic-Stops

conf/salt/project/web/gunicorn.conf
Increase gunicorn timeout to 120 seconds so workers have time to return API calls against large agencies before being killed prematurely. This is currently on ``master``, but got overridden while cleaning up ``conf/`` on dev while upgrading margarita. I deployed this branch to staging to test and now all graphs on large agencies, like Durham, load properly.
=> Restore increased gunicorn timeout

md/admin.py, md/data/copy.sql, md/data/importer.py, md/management/commands/md_constraints_sql.py, md/tests/test_normalization.py, tsdata/sql.py
Handled in this pull request:
- Add minimal admin support, matching that for NC
- Extract support for performing the import in a transaction from the NC code, add to MD code
- Verify that reloading MD data on a task will work (to support reloading new data into the same model on staging and production)
- Handle two-digit years for DOB greater than the current two-digit year. (The pandas datetime conversion didn't automatically make sense of two-digit years the way we want.)
This was previously planned but not implemented:
- "Add at least some test of the model. (NC has tests for API and other code that uses the model; we don't have such code yet. It seems like a good idea to have some test Real Soon.)"
A lot of tests were added in the original pull request, and I can't identify any …
=> ODPM-27 - MD data import improvements

traffic_stops/static/less/index.less, traffic_stops/templates/state.html
In addition to using flex layout to pin tab contents to the bottom of
the available space, this reduces them from `h2` to `h4` to make them more
compact and consistent with the headers below them.
=> ODPM-53: Style and structure changes to prevent tabs wrapping

traffic_stops/static/less/index.less
This makes two changes to tabs (both on state homepage and agency detail page):
* Their background color is now always grey, never white, even when they're active.
* ... except their background color becomes a slightly contrasting shade of grey when you hover the cursor over an inactive tab.
=> Changing color and hover behavior of tabs

package.json, traffic_stops/static/js/index.js
The graphs are failing on IE because I used `Object.assign`, which won't work on older browsers without `babel-polyfill`, which I forgot to include.
=> ODPM-57: Adding babel-polyfill requirement

traffic_stops/static/js/app/states/md/Stops.js, traffic_stops/static/js/app/states/nc/Stops.js, traffic_stops/static/less/index.less
This modifies the `tooltipContent` values for NC and MD stops pie charts to have smaller headers and to display integers.
The `h3` type (which is what the default `tooltipContent` seems to generate) is still used, with a modifying class, because doing otherwise seems to clog up NVD3's basic whitespace styles. Why fight it?
=> ODPM-55: Reformatting pie chart hover labels

nc/templates/nc.html
Having postponed slugs, I changed the id's of the top 5 agencies in the nc/templates/nc.html to make them match what's in the db.
=> change incorrect id's in nc top 5

traffic_stops/static/js/app/common/Stops.js, traffic_stops/static/js/app/states/md/Stops.js, traffic_stops/static/js/app/states/nc/Stops.js
Much of the code for NC and MD charts is identical except for a few details. It's possible to push the shared code into a `common/Stops.js` module and save `states/md/Stops.js` and `states/nc/Stops.js` for the unique stuff (which could itself be refactored, but this is a good start).
=> Refactoring stops

nc/tests/test_router.py, traffic_stops/routers.py, traffic_stops/settings/base.py
This pr changes the sig for allow_migrate in the router based on this change in Django 1.8 [](https://docs.djangoproject.com/en/1.8/releases/1.8/#deprecated-signature-of-allow-migrate)
It also refactors the logic a little bit and adds a test for the case of trying to apply a migration to the wrong state's db.
=> Odpm 54 new allow migrate sig

traffic_stops/static/less/index.less, traffic_stops/templates/agency_detail.html
Seemingly, dropping in an `officer_id` parameter "just works".
A suitable officer ID can be found by importing the Stop model from `md.models`, `filter`ing by `agency__name` (e.g. `"MSP"`), picking some arbitrary Stop, and getting the `officer_id`. Then you can construct a URL like `http://localhost:8000/md/agency/80/?officer_id=4735`.
As such, this patch just includes stylistic and template nudges to make it match the mockups.
=> ODPM-36 officer data

nc/templates/nc/agency_detail.html, traffic_stops/static/js/app/states/nc/Census.js, traffic_stops/static/less/index.less, traffic_stops/templates/agency_detail.html
Previously, the anchor links in the sticky header would move you down the page so far that the header itself obscured the target.
This adds some dynamically-set offsets to the targets (a combination of top padding and a negative top margin) to scroll the page only an appropriate amount.
Also, the census link, since it's always at the top of the page, is more easily set by just pointing the link at the top of the content wrapper.
=> ODPM-90: adding anchor offsets

traffic_stops/static/js/app/common/ContrabandHitRate.js, traffic_stops/static/js/app/common/LikelihoodOfSearch.js, traffic_stops/static/js/app/states/nc/Census.js, traffic_stops/static/js/app/states/nc/UseOfForce.js
Overly large hover labels no more! This rearranges the content of the Likelihood of Search graph's tooltips so as to be less obtrusive.
=> ODPM-87: Smaller labels on the Likelihood of Search graph

traffic_stops/static/js/app/common/ContrabandHitRate.js, traffic_stops/static/js/app/common/LikelihoodOfSearch.js, traffic_stops/static/js/app/common/Stops.js, traffic_stops/static/js/app/states/nc/Census.js
Internet Explorer, it appears, doesn't handle `svg` elements' `height` and `width` attributes like you'd expect, and the common workaround is to add CSS properties. This patch inserts those where relevant.
=> ODPM-62: fixing IE graph issues

.travis.yml, Makefile, md/data/MD_agencies.csv, md/data/analyzer.py, md/data/importer.py, md/templates/md.html, md/tests/test_normalization.py, traffic_stops/static/js/app/states/md/defaults.js
The full agency names are in a new ``.csv`` file under ``md/data`` which is used during import to update the pandas ``DataFrame`` with the full names.  This ``.csv`` also contains census ``GEOID`` values for some agencies, but those values aren't yet used.
The dataset facts in the MD landing page are updated to reflect the agency names and, as of a prior ticket, the dropping of 2012 data.
Lastly, the Python test coverage requirement is increased by a trivial amount which reflects a marginal coverage improvement with this pull request.
=> ODPM-32 - use full agency names

traffic_stops/static/js/app/base/TableBase.js, traffic_stops/static/less/index.less
Bootstrap's [responsive tables](http://getbootstrap.com/css/#tables-responsive) are a decent solution to our word-wrapping woes. With these, too-wide tables will simply be horizontally scrollable. No more word-wrapping.
=> ODPM-103: making dashboard tables responsive

traffic_stops/static/js/app/base/VisualBase.js, traffic_stops/static/js/app/common/ContrabandHitRate.js, traffic_stops/static/js/app/common/LikelihoodOfSearch.js, traffic_stops/static/js/app/common/Stops.js, traffic_stops/static/js/app/states/nc/Census.js, traffic_stops/static/js/app/states/nc/UseOfForce.js
The problem with IE before was fixed by assigning the `svg` elements fixed pixel widths and heights. This made them no longer *very small* on IE but broke their scaling behavior.
This adopts a more flexible solution. Pixel dimensions must still be used, as IE apparently demands this. But in order to preserve the flexible appearance of elements, we:
1. Set the dimensions on the basis of the parent container's dimensions & the view's built-in scaling factor
2. Watch for window resize events and re-set the dimensions of graphs
The size-updating callback defined on `VisualBase` includes a default implementation that is overridden on some inheritors of that class.
=> ODPM-101: improved graph scaling

md/templates/md.html, md/templates/md/agency_list.html, md/tests/test_api.py, md/tests/test_normalization.py, md/tests/test_views.py, md/urls.py, md/views.py, nc/templates/nc.html, nc/templates/nc/agency_list.html, nc/tests/test_api.py, nc/tests/test_views.py, nc/urls.py, nc/views.py, traffic_stops/base_views.py, traffic_stops/settings/dev.py, traffic_stops/static/js/affix.js, traffic_stops/static/js/app/states/nc/Census.js, traffic_stops/static/js/index.js, traffic_stops/static/less/index.less, traffic_stops/templates/agency_detail.html, traffic_stops/templates/agency_list.html, traffic_stops/templates/base.html, traffic_stops/templates/includes/navigation.html, traffic_stops/templates/state.html, traffic_stops/utils.py
This re-implements the "Find an Agency" pages for NC and MD to match the mockups and behave as requested, to whit:
1. Match mockup
2. Divide agencies alphabetically
The logic to divvy up agencies alphabetically lives on the back-end. It omits letters for which no agency exists. Tests have been added to verify this aggregation.
3. Give the user the option to search from the top
This is copied rotely from the state homepage.
4. Make the search bar sticky
Having found that the sticky header code for this and the agency detail page were mostly the same, I decided to refactor both to use a common JS module which now is imported in `index.js`.
5. Ensure this exists for MD as well as NC
6. Add a link to these pages from the state homepage
The mockups don't specify what this should look like, so …
=> ODPM-37: find an agency

md/admin.py, md/data/copy.sql, md/data/importer.py, md/migrations/0005_agency_census_profile_id.py, md/models.py, md/serializers.py, md/tests/test_api.py, nc/admin.py, nc/data/NC_agencies.csv, nc/data/copy.sql, nc/data/importer.py, nc/migrations/0002_agency_census_profile_id.py, nc/models.py, nc/serializers.py, nc/tests/test_api.py, tsdata/models.py, tsdata/tests/factories.py, tsdata/tests/test_census_profile.py
Importing the data will populate agency tables with census GEOID values when present in `{MD,NC}_agencies.csv`.
The agency API will return a dictionary of census data with the same racial and ethnic breakdowns as in `census.temporary.json`.  Source of census data is not provided.  (The front-end code currently
ignores the year from `census.temporary.json` anyway.)
`NC_agencies.csv` covers all of the small number of locales in `census.temporary.json` other than "Charlotte-Mecklenburg Police Department".
Future (after this pull request):
- front-end changes to use the new API (and remove  `census.temporary.json`)
- what census source to show on front-end for census data?
=> ODPM-65 - Provide census data if available via agency API

md/templates/md.html, md/tests/test_views.py, md/views.py, nc/templates/nc.html, nc/tests/test_views.py, nc/views.py, traffic_stops/static/less/index.less, traffic_stops/templates/state.html
Branched off Neil/Rebecca's branch. Let me know if it's easier for me to open this PR against dev.
I wasn't sure how to test this since it basically just GETs to another view entirely, but I wrote a basic test to verify the form exists. I also suggested an alternative form layout. Let me know what you all think.
=> Add Find a Stop form to tab on state homepages

traffic_stops/static/less/index.less
Because (I'm guessing) of some merge confusion, a critical piece of CSS got deleted; I did not notice this before I pushed because I didn't think that the Python text changes I made could affect CSS, but then again, other things were involved.
This restores the crucial piece of CSS and also adds a new rule to fix another style infelicity that I noticed while checking up on it.
=> Hotfix affix style

md/templates/md/search.html, nc/templates/nc/search.html, traffic_stops/settings/base.py, traffic_stops/static/less/index.less
> The search form is so large that it doesn't look like there are any results after searching, depending on your screen size (see attached screenshot). Some thoughts, but I don't know what the right answer is:
> The collapse button in the mockup may help
> Maybe the search form should default to collapsed after a search?
This adds a collapse button and defaults the form to collapsed after a search.
Note that the change to `STATICFILES_DIRS` is required in order to let Bootstrap find its fonts, which are used for the upwards and downward chevrons in the collapser element
=> ODPM-136: adding collapse toggle to search pages

nc/management/commands/prime_cache.py, nc/prime_cache.py
This is usually run manually to prime NC's cache. Looks like the Django 1.8 upgrade broke it.
=> Update prime cache sig to work for Django 1.8

traffic_stops/static/less/index.less, traffic_stops/templates/state.html
For whatever reason, Safari was causing adjacent col-8 and col-4 elements in a row to wrap. Weird! This patch suppresses row wrapping on large screens for `vertical-align` elements (which happen to be the ones we're interested in).
=> ODPM-128: Safari bugs

traffic_stops/static/less/index.less
For whatever reason, Safari is choosing to (flex-)wrap adjacent elements with width 66.66666667% and 33.33333333%. One might assume that these do not sum to > 100%, but life is funny that way.
This addresses the issue by simply re-implementing the `.vertical-align` class so as to not use flexbox but instead use explicit padding. This is less elegant and correct than flexbox, but since we have relatively few pages to worry about, we can definitely enumerate the spacing for each without it being a big deal.
=> ODPM-128: Safari flex-wrap bug, attempt #2

md/templates/md/search.html, nc/templates/nc/search.html
Fixes the problem of not being able to get at the Officer ID column on small screen widths.
To verify, view some search results ([example](http://localhost:8000/md/search/?agency=Montgomery+County+Sheriff%27s+Office&start_date=&end_date=&age=&ethnicity=&gender=&officer=)); turn on mobile emulation or narrow the window to < 400px; verify that you can scroll the results table to the right to see the Officer ID column.
=> ODPM-141: adding .responsive-table wrapper to search result tables

md/templates/md/agency_detail.html, nc/templates/nc/agency_detail.html, traffic_stops/static/less/index.less, traffic_stops/templates/agency_detail.html
IE has some weird behavior related to overflow hiding and scrolling. Well, maybe it's not weird: IE refuses to scroll to the top of an element when that top is not visible. It will only scroll to the highest visible point. All other browsers behave differently.
This new implementation of the scrolling fix dispenses with the padding trickery that made overflow-hiding necessary in the first place. Instead it uses an arealess floating `a` element positioned above the target and containing its ID. This has the further advantage of removing the need for extra JS.
To verify:
- Fire up IE.
- Go to an agency detail page.
- Click one of the links in the header (e.g. "Departmental Search Rate"). Verify that it scrolls in such a way that the headline text is visible.
- For good measure, do the same …
=> ODPM-130: New fix for anchor link scrolling

md/templates/md/agency_detail.html, traffic_stops/static/js/app/common/StopByReasonAndRace.js, traffic_stops/static/js/app/common/Stops.js, traffic_stops/static/js/app/states/md/StopByReasonAndRace.js, traffic_stops/static/js/app/states/md/index.js, traffic_stops/templates/agency_detail.html
Adds a "Departmental Stop Count" line graph to the Maryland pages.
Includes a `common/StopByReasonAndRace.js` base class in case we want to extend this to other states.
=> ODPM-92 stop by reason and race

md/forms.py, nc/forms.py, traffic_stops/templates/agency_detail.html
This responds to ticket ODPM-142 to make "Officer" read "Officer ID" on the search form and officer dashboard
=> change form text to Officer ID

traffic_stops/static/js/app/common/StopSearch.js
We want the lower bound on the Y axis of the "Average Departmental Search Rate For Vehicle Stops" to be 0, not whatever the lowest displayed value happens to be. This fixes the lower limit.
=> ODPM-147: Adding lower limit to StopSearch time series graph

traffic_stops/static/js/app/base/TableBase.js, traffic_stops/static/js/app/common/StopByReasonAndRace.js, traffic_stops/static/js/test/base/test_AggregateDataHandlerBase.js
This adds a `select` input (similar to the one on the line chart) to let the user limit the number of displayed items on the data table for stop counts.
The `add_select` method is very similar to `drawStartup` on the line chart; the only serious differences are:
- it will only add the `select` element once
- it includes a bit of scroll-updating logic so that the user's scroll position doesn't jump around disorientingly
The only other change is making it so that the `draw_table` method erases previously drawn tables and redraws from scratch.
=> Adding select input to filter Departmental Stop Count table

md/templates/md/agency_detail.html, nc/templates/nc/agency_detail.html
We changed "driving population" to "local population" in graphs but not in titles.
=> change driving population to local population in graph titles

.coveragerc, conf/pillar/project.sls, docs/data-import.rst, docs/dev-setup.rst, docs/il-data-normalization.rst, il/admin.py, il/data/IL_agencies.csv, il/data/__init__.py, il/data/analyzer.py, il/data/copy.sql, il/data/importer.py, il/management/commands/analyze_il.py, il/management/commands/il_constraints_sql.py, il/management/commands/import_il.py, il/migrations/0001_initial.py, il/migrations/0002_auto_20161006_0906.py, il/models.py, il/tests/factories.py, il/tests/test_models.py, il/tests/test_normalization.py, md/data/importer.py, nc/data/__init__.py, nc/management/commands/import_nc.py, traffic_stops/settings/base.py, tsdata/management/commands/import_census.py, tsdata/migrations/0004_auto_20161004_0743.py, tsdata/models.py, tsdata/tasks.py, tsdata/utils.py
This creates the "il" app with the ability to import the data and gather basic stats ("analyze_il") for the Illinois home page and for review by the client.
The initial .csv mapping of agency ids to names and census ids was created by a script which is not included in the source tree.  (Future modifications to the mapping are expected to be manual.)  The census mappings were created by dropping any trailing " Police" or " Police Department" from the agency name and seeing if that matches up with a census "city", "town", or "village".
`IL_TIME_ZONE` is used where it might be appropriate, though stop times are currently provided at year granularity so it isn't currently significant.
One area I don't understand is the SQL code to re-create constraints and corresponding command to display the …
=> ODPM-154 import illinois data

traffic_stops/static/less/index.less, traffic_stops/templates/state.html
As @copelco pointed out, the IL state graphic looks awkward when left-aligned on the state homepage (`il/`).
This centers it in its container, which looks less weird.
It's an open question whether we want to do this to the other state homepages for consistency's sake.
=> Centering IL state graphic on IL state homepage

traffic_stops/static/js/app/common/ContrabandHitRate.js, traffic_stops/static/js/app/common/LikelihoodOfSearch.js, traffic_stops/static/js/app/common/StopByReasonAndRace.js, traffic_stops/static/less/index.less
On charts that are preceded by help text that says something about using the chart's dropdown menu (e.g. the Departmental Stop Count chart), we'd like the dropdown to be closer to that text, i.e. above the chart and not after it.
This changes the `appendTo` call for dropdowns to `prependTo`, and it adjusts the appearance of those dropdowns' container elements to make them a bit more consistent and aesthetically acceptable.
These changes should be apparent on these charts:
- Departmental Stop Count
- Likelihood of Search by "Stop Cause"
- Contraband "Hit-Rate"
=> ODPM-164: prepending chart select dropdowns

README.rst, docs/index.rst, il/templates/il.html, il/templates/il/agency_detail.html, md/templates/md.html, md/templates/md/agency_detail.html, nc/templates/nc.html, nc/templates/nc/agency_detail.html, traffic_stops/static/js/app/common/StopByReasonAndRace.js, traffic_stops/templates/about.html
See Ian's email for details about requested changes. Each section of the doc is handled in a separate commit, for maximum clarity.
Katie also requested that the threshold change for "Departmental Stop Count" time series graphs (from 25% to 5%) be added to this ticket. You can verify this by going to, for example, `/md/agency/77/` and confirming that the Departmental Stop Count line chart includes lines for *Hispanic* and *Other*, both of them too low to register on the previous version.
=> ODPM-168: text updates

traffic_stops/static/less/index.less, traffic_stops/templates/home.html
The text on the homepage should be justified (newspaper-style).
The headlines of the homepage's text blocks are not justified, as this results in some very weird word spacing.
=> ODPM-168: Justifying homepage text

conf/pillar/production.sls, conf/pillar/project.sls, conf/salt/project/web/gunicorn.conf, docs/data-import.rst, nc/management/commands/prime_cache.py, nc/prime_cache.py, traffic_stops/settings/deploy.py
**BEFORE MERGING**: Change the branch in `conf/pillar/production.sls` back to `dev`.
What does this pull request do w.r.t. swap?
1. Lessen virtual memory requirements slightly by configuring Celery worker processes to exit after one task, as they will hold on to some of the memory used to import, and the same process might not be used again for months.  (This changed the Margarita version from 1.7.0 to 1.7.5.  See https://github.com/caktus/margarita/blob/develop/CHANGES.rst .)
2. Document how to manually manage swap for the IL data import.
What unrelated things does this pull request do?
1. Fix prime_cache management command so that it doesn't hard-code the old production server domain name, and allow it to be used on staging or production (i.e., user specifies host header).
2. Document …
=> ODPM-169 new prod machine swap space

conf/pillar/production.sls, conf/pillar/staging.sls, conf/salt/project/web/balancer.sls
With this addition to balancer.sls, letsencrypt will now use an arbitrarily long list of domains given in the environment's `letsencrypt_domains` list, instead of just the `pillar['domain']` value (which is its default).
The pertinent part of `balancer.sls` is (in particular, the `for` loop):
```
run_letsencrypt:
cmd.run:
- name: {{ letsencrypt_dir }}/letsencrypt-auto certonly --webroot --webroot-path {{ vars.public_dir }} {% for domain in letsencrypt_domains %}-d {{ domain }} {% endfor %} --email={{ pillar['admin_email'] }} --agree-tos --text --non-interactive
- unless: test -s /etc/letsencrypt/live/{{ pillar['domain'] }}/fullchain.pem -a -s /etc/letsencrypt/live/{{ pillar['domain'] }}/privkey.pem
- env:
- XDG_DATA_HOME: /root/letsencrypt
- require:
- git: install_letsencrypt
- file: …
```
=> Adding letsencrypt_domains for multi-domain certs

traffic_stops/static/less/index.less
Justified text looks horrible, just horrible, without word hyphenation.
On Chrome, [there's nothing we can do about that](http://caniuse.com/#feat=css-hyphens) without some kind of JS preprocessing.
But that's no reason to not take advantage of the handy CSS3 `hyphens` property that works on IE, Safari, and Firefox. Those visitors can enjoy text that looks quite nice with the addition of this one simple rule.
=> Add `hyphens: auto;` to `.justify` rules

nc/prime_cache.py
The normal way the affected code is run on production is in a Celery task, resulting in an exception.  (See comments in the new code.)
=> Bypass New Relic middleware bug when priming cache

nc/data/copy.sql, nc/migrations/0003_auto_20180115_1141.py, nc/models.py, nc/views.py
This change improves the query times for the stop search by adding an index to the date column and giving a hint to the query planner for computing the count. Locally I see the following improvement for the target search "/nc/search/?agency=NC+State+Highway+Patrol&start_date=02%2F01%2F2016&end_date=&age=&race=&ethnicity=&gender=&officer=" using debug toolbar.
Before change: 27055.24 ms (3 queries)
After change: 2296.81 ms (5 queries)
This is using date from 1/8/2018 which returns 1,007,953 results for the search.
=> [TRH-2688] Improve Search Query Time

nc/templates/nc/agency_detail.html
https://caktus.atlassian.net/browse/TRH-2694
The previous work on this ticket (#208) replaced graph/chart descriptions on the `agency_detail.html` page, which had the unintended consequence of affecting the department page, as well as the officer page. This pull request adds conditional logic to the `agency_detail.html` page so that one description shows up for the department page and statistics, and another description shows up for the officer page and statistics.
=> [TRH-2694] Department & Officer Graph/Chart Descriptions

traffic_stops/static/js/app/states/nc/ContrabandHitRate.js, traffic_stops/static/js/app/states/nc/LikelihoodOfSearch.js, traffic_stops/static/js/app/states/nc/StopSearch.js, traffic_stops/static/js/app/states/nc/Stops.js, traffic_stops/static/js/app/states/nc/defaults.js, traffic_stops/templates/agency_detail.html
Previous work (#213) removed the race/ethnicity toggle from the `agency_detail.html` page, but it also removed ethnicity data from the charts. Since the ticket did not ask us to remove the ethnicity data from the charts, this pull request adds that data back onto the `agency_detail.html` page. Also, the `race-selector` block has been re-added to the base template, since the ticket only specified removing it from the NC pages.
=> [TRH-2624] Re-Add Ethnicity Data To NC Agency Page

md/templates/md/agency_detail.html
This PR does the following:
- Restore MD chart titles to those on Production
- Chart titles are the same on both departmental and officer pages.
- The only chart title that should’ve changed, as listed on the original ticket ([TRH-2625](https://caktus.atlassian.net/browse/TRH-2625)) under the second AC:
> The table currently named "Average Officer Search Rate For Vehicle Stops" is named "Officer Search Rate for Vehicle Stops" on these single-officer pages
=> TRH-2739-Fix-MD-Chart-Titles

md/data/__init__.py, md/templates/md.html
Updated link to new merged data set. Values updated from the output of `python manage.py analyze_md`:
```
Dataset facts
Time frame: 2013-01-01 20:22:00 - 2017-12-31 23:59:00
Stops: 3,782,094
Searches: 113,961
Agencies: 131
Top five agencies:
Maryland State Police          1,092,912
Montgomery County Police Department 387,551
Baltimore County Police Department 351,616
Maryland Transportation Authority Police 293,524
Anne Arundel County Police Department 218,442
...
```
=> [TRH-2626] Update MD Data
