gulpfile.js, md/templates/md.html, md/views.py, package.json, traffic_stops/static/js/index.js, traffic_stops/static/less/index.less, traffic_stops/templates/state.html
This reforms the landing pages to meet the requirements given in OPDM-15, to whit:
- Real, computed stats are added to the Maryland landing page (with dead links and cryptic acronyms, but nevertheless).
- The search bar is moved higher up.
- A tabs widget (with a defunct second tab) is added to enclose "Agencies".
=> OPDM-15: landing pages

traffic_stops/static/less/index.less, traffic_stops/templates/includes/navigation.html
=> Putting conditional on nav bar `nav-inverse` class

md/api.py
This pr adds the following endpoints for completing the MD graphs. The data structure should match that for nc:
/md/api/agency/,id./searches/
/md/api/agency/,id./stops_by_reason/
/md/api/agency/,id./contraband_hit_rate/
provides number of searches and number of times contraband was seized per year and race
All of these endpoints are viewable in the browser
=> Odpm 66 additional endpoints

traffic_stops/static/js/app/common/Search.js, traffic_stops/static/js/app/common/Stops.js, traffic_stops/static/js/app/states/md/Search.js, traffic_stops/static/js/app/states/md/Stops.js, traffic_stops/static/js/app/states/nc/Search.js, traffic_stops/static/js/app/states/nc/Stops.js
Depends on #94.
Refactors Search graph code, by the sake token as the refactoring of Stops code.
=> Refactor Search

traffic_stops/static/js/app/common/LikelihoodOfSearch.js, traffic_stops/static/js/app/common/Search.js, traffic_stops/static/js/app/common/Stops.js, traffic_stops/static/js/app/states/md/LikelihoodOfSearch.js, traffic_stops/static/js/app/states/md/Search.js, traffic_stops/static/js/app/states/md/Stops.js, traffic_stops/static/js/app/states/nc/LikelihoodOfSearch.js, traffic_stops/static/js/app/states/nc/Search.js, traffic_stops/static/js/app/states/nc/Stops.js
=> Refactor likelihood of search

traffic_stops/static/js/app/common/StopSearch.js
This fixes the problem of spurious repetition of percents on the MD search rate graph.
=> Changing the tick format for MD

Makefile, md/data/importer.py, md/data/scanner.py, md/forms.py, md/templates/md/search.html, md/tests/factories.py, md/tests/test_api.py, md/tests/test_forms.py, md/tests/test_models.py, md/tests/test_normalization.py, md/tests/test_views.py, md/views.py, nc/forms.py, nc/templates/nc/search.html, nc/tests/factories.py, nc/tests/test_views.py, traffic_stops/static/js/app/states/md/index.js, traffic_stops/static/js/app/states/nc/index.js, traffic_stops/static/js/index.js, traffic_stops/static/less/index.less, traffic_stops/templates/search.html
This restyles the "Find a Stop" pages (`/md/search/`, `/nc/search/`) and sets up the MD page so that it actually works.
To validate, visit either of those pages and see if you can perform a search and see the results listed below the search form.
=> ODPM-35: find a stop (MD)

md/templates/md.html, traffic_stops/static/less/index.less, traffic_stops/templates/about.html, traffic_stops/templates/base.html, traffic_stops/templates/home.html, traffic_stops/templates/includes/navigation.html
This branch makes the changes in the ticket and all subtasks for ODPM-40
=> update page content

md/templates/md/search.html, nc/templates/nc/search.html, traffic_stops/templates/agency_list.html, traffic_stops/templates/base.html, traffic_stops/templates/search.html
Two fixes:
* changing the margins on header elements to match the same pulled-in style as on other pages
* changing the header button to link to the agencies list page
=> ODPM-135, ODPM-134: Find a Stop fixes

traffic_stops/static/less/index.less
See comment in code for explanation.
=> ODPM-131: responsive tables

md/forms.py, md/models.py
This restricts the available "Find a Stop" filters for MD to the subset `ENABLED_PURPOSES` of `PURPOSE_CHOICES`, reflecting our decision to omit two such choices.
=> ODPM-137: limiting purpose filters

traffic_stops/templates/base.html
Removes unwanted feedback widget
=> remove feedback widget from base template

traffic_stops/static/less/index.less
=> removed extra padding from footer in mobile

traffic_stops/static/js/app/states/md/defaults.js, traffic_stops/static/js/app/states/nc/defaults.js
This adds the new colors recommended by Basia Coulter.
It makes sure to match races/ethnicities to colors per her screenshot:
=> ODPM-143: Adding new color palette

md/templates/md/agency_detail.html, traffic_stops/static/js/app/common/StopByReasonAndRace.js, traffic_stops/static/js/app/states/md/StopByReasonAndRace.js
This pull request populates the "data" tab for the Departmental Stop Count graph.
=> add data chart for raw count of stops

md/templates/md/agency_detail.html
Changes to the MD graph captions, as requested by Ian.
NC captions are not altered.
=> Text changes

requirements/base.txt, traffic_stops/settings/base.py, traffic_stops/templates/base.html
Taken from [project template addition](https://github.com/caktus/django-project-template/pull/271/).
=> Adding cache-busting {{ REVISION }}

conf/manual/README.txt, conf/manual/traffic_stops-opendatapolicingnc.conf
See ODPM-178 for permanent solutions.
=> ODPM-170 - redirect old domain/URLs to new domain

nc/data/__init__.py
(It was in the import_nc management command file, but newer code places it here.)
=> Add this fix from the master branch

nc/management/commands/prime_cache.py, nc/prime_cache.py
Also, fix an exception when using the prime_cache mgmt command without setting the cutoff duration.
=> The HTTP request needs to use ALLOWED_HOSTS if set.

traffic_stops/settings/deploy.py
Colin has been getting exception e-mails directly.  He indicated that the other two people do not need to get them anymore.
=> Fix ADMINS for staging and production (use odp-team@caktusgroup.com)

nc/templates/nc/agency_detail.html, traffic_stops/static/js/app/states/nc/ContrabandHitRate.js, traffic_stops/static/js/app/states/nc/LikelihoodOfSearch.js, traffic_stops/static/js/app/states/nc/StopSearch.js, traffic_stops/static/js/app/states/nc/Stops.js, traffic_stops/static/js/app/states/nc/defaults.js, traffic_stops/templates/agency_detail.html
This PR removes the user facing aspects of the race/ethicity toggle including:
- the toggle itself
- Chart tables tab
=> TRH 2624 remove toggle

nc/data/copy.sql, nc/migrations/0003_auto_20180115_1141.py, nc/models.py, nc/views.py
Hotfix the query timeout fix from dev to master for a production release. Waiting on approval of the original issue before we move this forward.
=> [TRH-2688] Query Timeout Hotfix

md/templates/md/agency_detail.html
https://caktus.atlassian.net/browse/TRH-2625
This pull request updates the wording for graph titles and descriptions for MD officer pages to match the ticket description for TRH-2625. This is a follow-up on the work to update the officer pages for NC in #208.
=> [TRH-2625] MD Individual Officer Page Updates

traffic_stops/static/js/app/states/il/LikelihoodOfSearch.js, traffic_stops/static/js/app/states/md/LikelihoodOfSearch.js
A git bisect revealed the commit that caused the bug. I have now reverted it.
=> TRH-2734-fix-likelihood-chart

il/templates/il/agency_detail.html, md/templates/md/agency_detail.html, nc/templates/nc/agency_detail.html
This PR makes text changes to the explanatory text underneath the AC Census Data chart.
=> TRH-2811 Change AC Census Data Copy
